# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

repository: youngrok45/youngrok45.github.io

title: Youngrok's Homepage
email: youngrok45@gmail.com
description: I am Youngrok.
twitter_username: username
github_username: username
#minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
#theme: minimal-mistakes-jekyll
#minimal_mistakes_skin    : "air"
#minimal_mistakes_skin    : "aqua"
#minimal_mistakes_skin    : "contrast"
#minimal_mistakes_skin    : "dark"
#minimal_mistakes_skin    : "dirt"
#minimal_mistakes_skin    : "neon"
minimal_mistakes_skin    : "mint"
#minimal_mistakes_skin    : "plum"
#minimal_mistakes_skin    : "sunrise"
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Seoul

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Site Author
author:
  name             : "Youngrok Lee"
  avatar           : "/assets/images/bio-photo-1-rotated.png"
  bio              : ""
#  location         : "Seoul, South Korea"
#  email            : youngrok45@gmail.com
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/youngrok45/youngrok45.github.io"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:youngrok45@gmail.com"
    - label: "Seoul, South Korea"
      icon: "fas fa-map-marker-alt"
      url: "https://naver.me/x9BrQbEP"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/profile.php?id=100021146117689"


# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/youngrok45/youngrok45.github.io"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:youngrok45@gmail.com"
    - label: "Seoul, South Korea"
      icon: "fas fa-map-marker-alt"
      url: "https://naver.me/x9BrQbEP"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/profile.php?id=100021146117689"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
#      classes: wide
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      #classes: wide
      layout: single
      author_profile: true

category:
  type: liquid
  path: /categories/
tag:
  type: liquid
  path: /tags/
